#!/usr/bin/env sh
set -euo
echo "Checking"
go fmt .
go vet .
if command -v golint >/dev/null; then
	echo "Found golint, linting"
	find . -regex ".*\.go" -exec golint {} \;
else
	echo "Warning, couldn't find golint, not running" >&2
fi
if command -v gosec >/dev/null; then
	echo "Found gosec, checking for security issues..."
	gosec .
else
	echo "Warning, couldn't find gosec, not running" >&2
fi
echo "Finished linting, no issues!"
