#!/usr/bin/env sh
set -euo
echo "Checking"
go fmt
if command -v gofumpt >/dev/null; then
	gofumpt -s -w .
fi
if command -v golangci-lint >/dev/null; then
	golangci-lint run \
		-E bodyclose \
		-E noctx \
		-E golint \
		-E rowserrcheck \
		-E gosec \
		-E unconvert \
		-E dupl \
		-E asciicheck \
		-E gofmt \
		-E gofumpt \
		-E goimports \
		-E goheader \
		-E maligned \
		-E misspell \
		-E lll \
		-E unparam \
		-E dogsled \
		-E nakedret \
		-E prealloc \
		-E gocritic \
		-E gochecknoinits \
		-E funlen \
		-E goprintffuncname \
		-E goerr113 \
		-E godot \
		-E testpackage \
		-E nestif \
		-E exportloopref \
		-E exhaustive \
		-E sqlclosecheck \
		-E nlreturn \
		-E nolintlint
	echo "Finished linting, no issues!"
	exit 0
else
	echo "Failed to lint" >&2
	exit 1
fi
