name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Setup environment
      run: sudo apt-get update && sudo apt-get install -y fortune cowsay
    - name: Super-Linter
      uses: github/super-linter@v2.0.0
